#!/usr/bin/env python3
"""Generate development-only TLS certificates for the local Flower federation.

The generated CA private key and SuperLink private key are intentionally
excluded from Git. Production certificates must come from the organization's
PKI and must not be generated by this utility.
"""

from __future__ import annotations

import argparse
import shutil
import subprocess
from pathlib import Path


def run_openssl(args: list[str]) -> None:
    """Run OpenSSL and fail clearly when it is unavailable."""

    if shutil.which("openssl") is None:
        raise RuntimeError("OpenSSL is required to generate development certificates.")
    subprocess.run(["openssl", *args], check=True)


def generate_certificates(output_dir: Path, superlink_host: str) -> None:
    """Generate a local CA and a SuperLink certificate with DNS/IP SANs."""

    output_dir.mkdir(parents=True, exist_ok=True)

    ca_key = output_dir / "ca.key"
    ca_cert = output_dir / "ca.crt"
    superlink_key = output_dir / "superlink.key"
    superlink_csr = output_dir / "superlink.csr"
    superlink_cert = output_dir / "superlink.crt"
    ext_file = output_dir / "superlink.ext"

    run_openssl(["genrsa", "-out", str(ca_key), "4096"])
    run_openssl([
        "req", "-x509", "-new", "-nodes", "-key", str(ca_key),
        "-sha256", "-days", "365", "-out", str(ca_cert),
        "-subj", "/CN=FederatedHomes Development CA",
    ])

    run_openssl(["genrsa", "-out", str(superlink_key), "2048"])
    run_openssl([
        "req", "-new", "-key", str(superlink_key),
        "-out", str(superlink_csr), "-subj", "/CN=superlink",
    ])

    san = f"DNS:{superlink_host},DNS:localhost,IP:127.0.0.1"
    ext_file.write_text(
        "basicConstraints=CA:FALSE\n"
        "keyUsage=digitalSignature,keyEncipherment\n"
        "extendedKeyUsage=serverAuth\n"
        f"subjectAltName={san}\n",
        encoding="utf-8",
    )

    run_openssl([
        "x509", "-req", "-in", str(superlink_csr),
        "-CA", str(ca_cert), "-CAkey", str(ca_key),
        "-CAcreateserial", "-out", str(superlink_cert),
        "-days", "365", "-sha256", "-extfile", str(ext_file),
    ])

    superlink_csr.unlink(missing_ok=True)
    ext_file.unlink(missing_ok=True)
    (output_dir / "ca.srl").unlink(missing_ok=True)

    for path in (ca_key, superlink_key):
        path.chmod(0o600)

    print(f"Generated development certificates in {output_dir}")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output-dir",
        default="certificates/dev",
        type=Path,
        help="Directory for generated development certificates",
    )
    parser.add_argument(
        "--superlink-host",
        default="superlink",
        help="DNS name used by SuperNodes to reach SuperLink",
    )
    args = parser.parse_args()
    generate_certificates(args.output_dir, args.superlink_host)


if __name__ == "__main__":
    main()
