FROM flwr/superexec:1.33.0

WORKDIR /app
RUN mkdir -p /app/.flwr/apps && chmod -R a+rwx /app/.flwr

ENV PIP_EXTRA_INDEX_URL=https://download.pytorch.org/whl/cpu

# Install additional runtime dependencies not provided by the base flwr/superexec:1.33.0 image.
COPY requirements.txt /app/
RUN python -m pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

# Copy only the files required for the app runtime.
COPY src/ /app/src/
COPY .flwr/config.toml /app/.flwr/config.toml

ENTRYPOINT ["flower-superexec"]
